# Generated by Django 5.1.5 on 2025-01-19 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('default_value', 'Default Value'), ('Informe tecnico', 'Informe Técnico'), ('Acta de congreso', 'Acta de Congreso'), ('Revista cientifica', 'Revista Científica')], default='default_value', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('nationality', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
            },
        ),
        migrations.CreateModel(
            name='ResearchGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('line', models.CharField(max_length=60)),
                ('categoria', models.CharField(choices=[('Categoría A', 'A'), ('Categoría B', 'B'), ('Categoría C', 'C'), ('Categoría D', 'D'), ('Categoría E', 'E')], max_length=12)),
            ],
            options={
                'verbose_name': 'Grupo de Investigación',
                'verbose_name_plural': 'Grupos de Investigación',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('publication_date', models.DateField()),
                ('id_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.articletype')),
                ('id_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.author')),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
            },
        ),
        migrations.CreateModel(
            name='CongressProceedings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('year_firstedition', models.IntegerField()),
                ('frecuency', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('id_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.article')),
            ],
            options={
                'verbose_name': 'Acta de Congreso',
                'verbose_name_plural': 'Actas de Congreso',
            },
        ),
        migrations.AddField(
            model_name='author',
            name='id_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.researchgroup'),
        ),
        migrations.CreateModel(
            name='ScientificJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('editor', models.CharField(max_length=100)),
                ('start_year', models.DateField(max_length=50)),
                ('periodicity', models.CharField(max_length=50)),
                ('topic', models.DateField(max_length=50)),
                ('edicion_number', models.IntegerField()),
                ('pages', models.IntegerField()),
                ('pusblication_year', models.DateField()),
                ('id_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.article')),
            ],
            options={
                'verbose_name': 'Revista Científica',
                'verbose_name_plural': 'Revistas Científicas',
            },
        ),
        migrations.CreateModel(
            name='TechnicalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('publishing_center', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('id_articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.article')),
            ],
            options={
                'verbose_name': 'Informe Técnico',
                'verbose_name_plural': 'Informes Técnicos',
            },
        ),
    ]
