# Generated by Django 5.1.5 on 2025-01-23 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scientificjournal',
            name='pusblication_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='scientificjournal',
            name='start_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='scientificjournal',
            name='topic',
            field=models.CharField(max_length=50),
        ),
    ]
