# Generated by Django 5.1.5 on 2025-01-25 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_alter_scientificjournal_pusblication_year_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technicalreport',
            old_name='id_articulo',
            new_name='id_article',
        ),
    ]
