# Generated by Django 5.1.5 on 2025-01-25 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_rename_id_articulo_technicalreport_id_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scientificjournal',
            old_name='pusblication_year',
            new_name='publication_year',
        ),
    ]
